backend:
  name: github
  repo: freeserverproject/freeserver-wiki
media_folder: "docs/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - {
              label: "Hero image",
              name: "heroImage",
              widget: "image",
              required: false,
            }
          - { label: "Hero text", name: "heroText", widget: "string" }
          - {
              label: "Tagline",
              name: "tagline",
              widget: "string",
              required: false,
            }
          - { label: "Action text", name: "actionText", widget: "string" }
          - { label: "Action link", name: "actionLink", widget: "string" }
          - label: Features
            name: features
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Details", name: "details", widget: "string" }
          - {
              label: "Footer",
              name: "footer",
              widget: "string",
              required: false,
            }
          - { label: "Body", name: body, widget: markdown, required: false }
  - label: "固定ページ"
    name: "fixedPages"
    folder: "docs"
    filter: {field: "language", value: false}
    create: true
    fields:
      - { label: "Home", name: "home", widget: "hidden", default: false }
      - { label: "ページ名", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "運営一覧"
    name: "admins"
    folder: "docs/admins"
    create: true
    fields:
      - { label: "ユーザー名", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
  - label: "イベント"
    name: "events"
    folder: "docs/events"
    create: true
    fields:
      - { label: "イベント名", name: "title", widget: "string" }
      - { label: "説明", name: "description", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }